### ISSUE TITLE
Corrupt json data causes api to panic. Empty reply from the server

### ISSUE THREAD

**Issue by tanmayambre** [univedo/api2go#103]
While doing a PUT request using data not expected by the server. i.e. Bad json data that cannot be un-marshalled.
curl 'localhost:8080/structure/XXX-YYYY' -X PUT --data '{"data":{"integerfield":"iamsendingstringinstead"}}'

i get "Empty reply from server"
I sent a string field while GO data structure expects a integer.

Should it not send an appropriate error code back?

Here is the stack trace.
Stack trace:
```
2015/04/16 14:18:22 http: panic serving 127.0.0.1:53678: reflect: call of reflect.Value.Float on string Value
goroutine 84 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
reflect.Value.Float(0x72dfa0, 0xc2081774e0, 0x58, 0x7eff76fdf9e8)
	/usr/local/go/src/reflect/value.go:787 +0xb6
github.com/univedo/api2go/jsonapi.setFieldValue(0xc20812d320, 0x72dfa0, 0xc2081774e0, 0x58)
	/home/bellrock1/gocode/src/github.com/univedo/api2go/jsonapi/unmarshal.go:198 +0x9d
github.com/univedo/api2go/jsonapi.UnmarshalInto(0xc208126c00, 0x7eff76fdf9e8, 0x836a80, 0xc20812d2e0, 0x0, 0x0)
	/home/bellrock1/gocode/src/github.com/univedo/api2go/jsonapi/unmarshal.go:174 +0x2002
github.com/univedo/api2go.(*resource).handleUpdate(0xc2080cd740, 0x7eff76fe5620, 0xc208076280, 0xc2080321a0, 0xc20812c060, 0x1, 0x1, 0x0, 0x0)
	/home/bellrock1/gocode/src/github.com/univedo/api2go/api.go:294 +0x394
github.com/univedo/api2go.func·008(0x7eff76fe5620, 0xc208076280, 0xc2080321a0, 0xc20812c060, 0x1, 0x1)
	/home/bellrock1/gocode/src/github.com/univedo/api2go/api.go:144 +0x69
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc2080ccc90, 0x7eff76fe5620, 0xc208076280, 0xc2080321a0)
	/home/bellrock1/gocode/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e
net/http.serverHandler.ServeHTTP(0xc20805a1e0, 0x7eff76fe5620, 0xc208076280, 0xc2080321a0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208076140)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by wwwdata** [comment]
thanks for this bug report, we will write a test for it and fix it
